import { useEffect } from "react";
import { Logo } from "@/components/Logo";
import { Link, useLocation } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CodeBlock } from "@/components/CodeBlock";
import { apiClient } from "@/integrations/api/client";
import { usePageMeta } from "@/hooks/usePageMeta";
import { fmtCompact, fmtInt, fmtPct } from "@/lib/catalog-display";
import { QuickStartHubs } from "@/components/QuickStartHubs";

const Mono = ({ children }: { children: React.ReactNode }) => <code className="code-inline">{children}</code>;

const STEPS = [
  {
    title: "Download",
    body: "Raw reads for every sample (GSM) in the study are fetched from SRA. Samples whose runs are missing, withdrawn or single-ended for a droplet protocol are recorded as failed at this step, not silently dropped.",
  },
  {
    title: "Protocol detection",
    body: "The library type (10x 3' v2/v3, 10x 5', Drop-seq, CITE-seq, BD Rhapsody, Smart-seq, …) is detected from the reads and the GEO/SRA metadata so the right barcode and UMI layout is applied. Samples where no chemistry can be confirmed are labelled \"10x (protocol unconfirmed)\" in the catalog.",
  },
  {
    title: "Alignment and counting",
    body: "Reads are mapped to a single reference per organism (see below) and counted per cell barcode and gene, separately for exonic and intronic reads, plus splice junctions. Every sample in the atlas is processed with the same pipeline version and parameters.",
  },
  {
    title: "Per-sample QC",
    body: "Cells are called, and each sample gets mapping rate, cells called, median genes and UMIs per cell and mitochondrial fraction. A sample that falls under the minimum thresholds is kept in the catalog and marked failed with the reason.",
  },
  {
    title: "One .singlet bundle per study",
    body: "All processed samples of a study are packed into one .singlet file (a ZIP64 archive of sparse matrices and JSON metadata) and published for free download. Nothing is re-normalised or batch-corrected; you get raw counts.",
  },
];

function useHashScroll() {
  const { hash } = useLocation();
  useEffect(() => {
    if (!hash) return;
    const id = decodeURIComponent(hash.slice(1));
    const t = setTimeout(() => document.getElementById(id)?.scrollIntoView({ block: "start" }), 40);
    return () => clearTimeout(t);
  }, [hash]);
}

const About = () => {
  usePageMeta({
    title: "About the data",
    description: "How every study in the singlet atlas is processed, which references are used, processing status, license (CC0 data, MIT code) and how to cite.",
    path: "/about",
  });
  useHashScroll();

  const { data: stats } = useQuery({ queryKey: ["corpus-stats"], queryFn: () => apiClient.stats(), staleTime: 120_000 });

  const year = new Date().getFullYear();

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Navbar />
      <main className="container-site flex-1 py-10 md:py-14">
        <article className="prose-doc max-w-[760px]">
          <header className="mb-10">
            <Logo variant="mark" height={28} link={false} className="docs-brand-mark mb-4" />
              <h1 className="text-[36px] md:text-[42px] mb-3">About the data</h1>
            <p className="text-[17px] text-muted-foreground">
              The atlas is every public single-cell RNA-seq study on GEO that the pipeline can process, reprocessed from
              raw reads the same way, so numbers from different labs are directly comparable.
            </p>
          </header>

          {/* ── Where this comes from ── */}
          <section id="sources" className="pb-12 mb-12 border-b border-border scroll-mt-20">
            <h2>Where the catalog and the data come from</h2>
            <p>
              Search, facets and the counts shown on this site come from our own reprocessed index — a database built
              from running every study through the pipeline. The actual data you download is not generated by that
              index: it is the published <Mono>.singlet</Mono> bundle for the study, produced once and served as-is from
              <Mono> data.singlet.bio</Mono>. If the two ever disagree (for example the index says a study has a bundle
              but the file is missing), the file is the source of truth.
            </p>
            <p>
              List and export endpoints are capped so the service stays fast and free for everyone: search result pages
              are paginated, a bulk <Mono>/api/manifest</Mono> export covers at most 2,000 studies per request, and
              accession exports are capped at 5,000. None of these caps apply to loading or downloading a study you
              already know the accession for.
            </p>
          </section>

          {/* ── Quick start ── */}
          <section id="quick-start" className="pb-12 mb-12 border-b border-border scroll-mt-20">
            <h2>Jump into the atlas</h2>
            <p className="mb-4">A few common starting points, with a live study count for each.</p>
            <QuickStartHubs title="Quick start" />
          </section>

          {/* ── Processing ── */}
          <section id="processing" className="pb-12 mb-12 border-b border-border scroll-mt-20">
            <h2>What a study goes through</h2>
            <ol className="!list-none !pl-0 space-y-4 mt-5">
              {STEPS.map((s, i) => (
                <li key={s.title} className="flex gap-4">
                  <span className="font-mono text-[13px] text-primary tabular pt-0.5 w-6 shrink-0">{String(i + 1).padStart(2, "0")}</span>
                  <div>
                    <h3 className="!mt-0 !mb-1">{s.title}</h3>
                    <p className="!mb-0 text-[14.5px]">{s.body}</p>
                  </div>
                </li>
              ))}
            </ol>
          </section>

          {/* ── References ── */}
          <section id="references" className="pb-12 mb-12 border-b border-border scroll-mt-20">
            <h2>References</h2>
            <p>One reference build per organism, used for every sample of that organism:</p>
            <table>
              <thead>
                <tr>
                  <th>Organism</th>
                  <th>Genome build</th>
                  <th>Annotation</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Human</td>
                  <td><Mono>GRCh38</Mono> (2024-A build)</td>
                  <td>GENCODE v44 (equivalently Ensembl 110)</td>
                </tr>
                <tr>
                  <td>Mouse</td>
                  <td><Mono>GRCm39</Mono> (2024-A build)</td>
                  <td>GENCODE vM33 (equivalently Ensembl 110)</td>
                </tr>
                <tr>
                  <td>Rat</td>
                  <td><Mono>mRatBN7.2</Mono></td>
                  <td>Ensembl 110</td>
                </tr>
                <tr>
                  <td>All other organisms</td>
                  <td>Latest Ensembl or NCBI RefSeq assembly for the species</td>
                  <td>Ensembl 115, Ensembl Rapid Release, or NCBI RefSeq</td>
                </tr>
              </tbody>
            </table>
            <p>
              GENCODE only publishes human and mouse annotation, so every other organism is built from Ensembl (release
              115 for the main vertebrate set, Rapid Release for species that are not yet in the main Ensembl release) or
              from NCBI RefSeq for plants, fungi, protists and bacteria. There are currently 65 organism builds, plus a
              combined human + mouse <Mono>GRCh38-GRCm39</Mono> barnyard build used for species-mixing experiments.
            </p>
            <p>
              For the human 2024-A build the genome FASTA is taken from Ensembl 109 (GRCh38.p13) rather than 110, because
              release 110 ships an unmasked pseudoautosomal region on chrY; the GTF is GENCODE v44. Mouse 2024-A uses the
              Ensembl 110 FASTA with the GENCODE vM33 GTF.
            </p>
            <p>
              The build a sample was mapped to is recorded per cell in <Mono>obs["reference_build"]</Mono> and in the
              bundle's <Mono>feature_vocab.json</Mono>, so gene ids are always interpretable.
            </p>
          </section>

          {/* ── Status ── */}
          <section id="status" className="pb-12 mb-12 border-b border-border scroll-mt-20">
            <h2>Processing status</h2>
            <p>
              We are continuing to perform data reprocessing today. Here are live updates on the state of our continually
              growing catalog.
            </p>

            <h3>Available to download now</h3>
            <p className="text-[14.5px]">
              These are the same numbers shown on the home page: studies that have a published{" "}
              <Mono>.singlet</Mono> file you can download right now.
            </p>
            <dl className="grid grid-cols-2 md:grid-cols-3 gap-3 my-5">
              {[
                { label: "studies with files", value: stats ? fmtInt(stats.studies_with_files) : null },
                { label: "samples in files", value: stats ? fmtInt(stats.samples_in_files) : null },
                { label: "cells called in files", value: stats ? fmtCompact(stats.cells_in_files) : null },
              ].map((s) => (
                <div key={s.label} className="surface px-4 py-3">
                  <dd className="font-display font-bold text-[24px] leading-none tabular text-foreground">
                    {s.value ?? <span className="inline-block h-6 w-16 rounded bg-secondary animate-pulse" />}
                  </dd>
                  <dt className="mt-1.5 text-xs text-muted-foreground">{s.label}</dt>
                </div>
              ))}
            </dl>

            <h3>Processed so far</h3>
            <p className="text-[14.5px]">
              Samples the pipeline has already finished. Packing and publishing runs behind processing, so these numbers
              are larger than the download numbers above — the difference is the queue of finished samples whose study
              bundle has not been published yet.
            </p>
            <dl className="grid grid-cols-2 md:grid-cols-4 gap-3 my-5">
              {[
                { label: "studies in catalog", value: stats ? fmtInt(stats.series_count) : null },
                { label: "samples processed", value: stats ? fmtInt(stats.success_samples) : null },
                { label: "cells called", value: stats ? fmtCompact(stats.total_cells) : null },
                { label: "success rate", value: stats ? fmtPct(stats.success_rate) : null },
              ].map((s) => (
                <div key={s.label} className="surface px-4 py-3">
                  <dd className="font-display font-bold text-[24px] leading-none tabular text-foreground">
                    {s.value ?? <span className="inline-block h-6 w-16 rounded bg-secondary animate-pulse" />}
                  </dd>
                  <dt className="mt-1.5 text-xs text-muted-foreground">{s.label}</dt>
                </div>
              ))}
            </dl>
            {stats && (
              <p className="text-[13.5px] text-muted-foreground">
                Mean mapping rate {fmtPct(stats.avg_mapping_rate)}; mean median genes per cell{" "}
                {fmtInt(stats.avg_median_genes)}. Cell counts for a small number of plate-based samples are withheld while
                a known counting bug is corrected upstream.
              </p>
            )}
          </section>

          {/* ── License & citation ── */}
          <section id="cite" className="pb-12 mb-12 border-b border-border scroll-mt-20">
            <h2>License and citation</h2>
            <p>
              The atlas data is dedicated to the public domain under{" "}
              <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener noreferrer">CC0 1.0</a>.
              You can use it for anything, including commercial work, with no attribution requirement. The{" "}
              <Mono>singlet</Mono> software is{" "}
              <a href="https://github.com/Singlet-Bio/singlet/blob/main/LICENSE" target="_blank" rel="noopener noreferrer">MIT licensed</a>.
              Details are on the <Link to="/data-license">license page</Link>.
            </p>
            <h3>How to cite</h3>
            <p>
              Please cite both the original study and the atlas release you used. The original study is the GEO accession
              and its publication (linked from every study page); the atlas release is the <Mono>singlet_version</Mono>{" "}
              recorded in the file manifest and on the study page.
            </p>
            <CodeBlock
              label="text"
              code={`<Original authors>. <Title>. GEO accession GSE178957 (<year>).
Singlet Bio. singlet atlas, release <singlet_version>. https://singlet.bio (accessed ${year}).`}
            />
          </section>

          {/* ── Contact ── */}
          <section id="contact" className="scroll-mt-20">
            <h2>Contact</h2>
            <p>
              Questions, a study that looks wrong, or a protocol we should support: open an issue on{" "}
              <a href="https://github.com/Singlet-Bio/singlet/issues" target="_blank" rel="noopener noreferrer">GitHub Issues</a>.
              Processing runs on NSF ACCESS allocations; the data is served from our CDN at no cost to you.
            </p>
          </section>
        </article>
      </main>
      <Footer />
    </div>
  );
};

export default About;
