// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function makeStubClient(): SupabaseClient<Database> {
  const queryError = { data: null, error: new Error('Supabase client not configured: missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY at build time'), count: null };
  const queryThenable = {
    select: () => queryThenable,
    insert: () => queryThenable,
    update: () => queryThenable,
    upsert: () => queryThenable,
    delete: () => queryThenable,
    eq: () => queryThenable,
    neq: () => queryThenable,
    in: () => queryThenable,
    is: () => queryThenable,
    not: () => queryThenable,
    or: () => queryThenable,
    order: () => queryThenable,
    limit: () => queryThenable,
    range: () => queryThenable,
    single: () => queryThenable,
    maybeSingle: () => queryThenable,
    then: (resolve: (v: typeof queryError) => unknown) => Promise.resolve(queryError).then(resolve),
  };
  const stub = {
    from: () => queryThenable,
    rpc: () => Promise.resolve(queryError),
    auth: {
      getSession: () => Promise.resolve({ data: { session: null }, error: null }),
      getUser: () => Promise.resolve({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      signInWithPassword: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Auth unavailable') }),
      signInWithOAuth: () => Promise.resolve({ data: { url: null, provider: null }, error: new Error('Auth unavailable') }),
      signOut: () => Promise.resolve({ error: null }),
      setSession: () => Promise.resolve({ data: { user: null, session: null }, error: new Error('Auth unavailable') }),
    },
    functions: {
      invoke: () => Promise.resolve(queryError),
    },
  };
  return stub as unknown as SupabaseClient<Database>;
}

const hasValidConfig = !!SUPABASE_URL && /^https?:\/\//i.test(SUPABASE_URL) && !!SUPABASE_PUBLISHABLE_KEY;

if (!hasValidConfig && typeof window !== 'undefined') {
  // eslint-disable-next-line no-console
  console.warn('[supabase] VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY missing — using stub client; backend features disabled.');
}

export const supabase: SupabaseClient<Database> = hasValidConfig
  ? createClient<Database>(SUPABASE_URL as string, SUPABASE_PUBLISHABLE_KEY as string, {
      auth: {
        storage: brokeredPreviewStorage(),
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : makeStubClient();
